# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Tom/VB_ZB/VB_ZB.cache/wt [current_project]
set_property parent.project_path C:/Users/Tom/VB_ZB/VB_ZB.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo c:/Users/Tom/VB_ZB/VB_ZB.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/Tom/Desktop/tobudx.coe
read_verilog -library xil_defaultlib {
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/alu.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/new/anti_vibration.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/boy.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/brom.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/clk_div.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/control.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/cpu.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/dma.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/mbc5.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/ppu.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/regfile.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/serial.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/singleport_ram.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/singlereg.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_channel_mix.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_length_ctr.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_noise.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_square.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_vol_env.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/sound_wave.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/timer.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/vga_mixer.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/vga_timing.v
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/new/top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/ADAU1761_interface.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/adau1761_configuraiton_data.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/adau1761_izedboard.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/audio_top.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/clocking.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/i2c.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/i2s_data_interface.vhd
  C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/imports/rtl/i3c2.vhd
}
read_ip -quiet C:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/pll/pll.xci
set_property used_in_implementation false [get_files -all c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/pll/pll_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/pll/pll.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/pll/pll_ooc.xdc]

read_ip -quiet c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu.xci
set_property used_in_implementation false [get_files -all c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu_ooc.xdc]

read_ip -quiet c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/vga_mem/vga_mem.xci
set_property used_in_implementation false [get_files -all c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/vga_mem/vga_mem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Tom/VB_ZB/VB_ZB.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files C:/Users/Tom/VB_ZB/VB_ZB.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
