# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu.xci
# IP: The module: 'CartTobu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CartTobu'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu.xci
# IP: The module: 'CartTobu' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Tom/VB_ZB/VB_ZB.srcs/sources_1/ip/CartTobu/CartTobu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CartTobu'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
